export enum OnboardingStatus {
  PLAN_REQUIRED = 'PLAN_REQUIRED',
  WORKSPACE_ACTIVATION = 'WORKSPACE_ACTIVATION',
  GETTING_STARTED_VIDEO = 'GETTING_STARTED_VIDEO',
  PROFILE_CREATION = 'PROFILE_CREATION',
  SYNC_EMAIL = 'SYNC_EMAIL',
  APPS_INSTALLATION = 'APPS_INSTALLATION',
  INVITE_TEAM = 'INVITE_TEAM',
  BOOK_CALL = 'BOOK_CALL',
  COMPLETED = 'COMPLETED',
}
