export enum McpConnectionExceptionCode {
  CONNECTION_NOT_FOUND = 'CONNECTION_NOT_FOUND',
  DISCOVERY_FAILED = 'DISCOVERY_FAILED',
  DYNAMIC_CLIENT_REGISTRATION_FAILED = 'DYNAMIC_CLIENT_REGISTRATION_FAILED',
  CLIENT_CREDENTIALS_NOT_CONFIGURED = 'CLIENT_CREDENTIALS_NOT_CONFIGURED',
  TOKEN_EXCHANGE_FAILED = 'TOKEN_EXCHANGE_FAILED',
  REFRESH_FAILED = 'REFRESH_FAILED',
  INVALID_STATE = 'INVALID_STATE',
  INVALID_REQUEST = 'INVALID_REQUEST',
  FORBIDDEN = 'FORBIDDEN',
  MCP_REQUEST_FAILED = 'MCP_REQUEST_FAILED',
  TOOL_NOT_FOUND = 'TOOL_NOT_FOUND',
}
