export const STALLED_AFTER_DAYS_VARIABLE_NAME = 'STALLED_AFTER_DAYS';
export const CLOSED_STAGES_VARIABLE_NAME = 'CLOSED_STAGES';

export const DEFAULT_STALLED_AFTER_DAYS = 21;
export const DEFAULT_CLOSED_STAGES = ['CUSTOMER'];

export const NIGHTLY_SCORING_CRON_PATTERN = '0 5 * * *';
